### ISSUE TITLE
Update to Qt 5.15.0

### ISSUE THREAD

**Issue by berolinux** [OpenMandrivaAssociation/qt5#1]
This needs rebuilding all of KDE and a few other packages (anything containing Qt plugins at least) and will break Cooker between the time qt5-qtbase is built and the time the last dependency is rebuilt.

**Comment by benbullard79** [comment]
My changes were me noodling around getting used to the board.
They don't reflect any knowledge of what was actually happening with this process.
Apologies.

**Comment by omakuta** [comment]
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/probleme-suite-a-la-migration-rolling-vers-cooker/3404/2

**Comment by tpgxyz** [comment]
Done
